export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        bg: 'rgb(var(--bg) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'surface-2': 'rgb(var(--surface-2) / <alpha-value>)',
        border: 'rgb(var(--border) / <alpha-value>)',
        'border-strong': 'rgb(var(--border-strong) / <alpha-value>)',
        text: 'rgb(var(--text) / <alpha-value>)',
        'text-muted': 'rgb(var(--text-muted) / <alpha-value>)',
        accent: 'rgb(var(--accent) / <alpha-value>)',
        'accent-hover': 'rgb(var(--accent-hover) / <alpha-value>)',
        'on-accent': 'rgb(var(--on-accent) / <alpha-value>)',
        terracotta: 'rgb(var(--terracotta) / <alpha-value>)',
        'terracotta-ink': 'rgb(var(--terracotta-ink) / <alpha-value>)',
        gold: 'rgb(var(--gold) / <alpha-value>)',
        'gold-ink': 'rgb(var(--gold-ink) / <alpha-value>)',
        'on-gold': 'rgb(var(--on-gold) / <alpha-value>)',
        danger: 'rgb(var(--danger) / <alpha-value>)',
        'on-danger': 'rgb(var(--on-danger) / <alpha-value>)',
        alert: 'rgb(var(--alert) / <alpha-value>)',
        'on-alert': 'rgb(var(--on-alert) / <alpha-value>)',
        crimson: 'rgb(var(--danger) / <alpha-value>)',
        'on-crimson': 'rgb(var(--on-danger) / <alpha-value>)',
        burgundy: 'rgb(var(--danger) / <alpha-value>)',

        rail: 'rgb(var(--rail) / <alpha-value>)',
        'rail-hover': 'rgb(var(--rail-hover) / <alpha-value>)',
        'rail-ink': 'rgb(var(--rail-ink) / <alpha-value>)',
        'rail-ink-muted': 'rgb(var(--rail-ink-muted) / <alpha-value>)',
        'rail-mark': 'rgb(var(--rail-mark) / <alpha-value>)',
        'rail-edge': 'rgb(var(--rail-edge) / <alpha-value>)',
        
        cta: 'rgb(var(--cta) / <alpha-value>)',
        'cta-hover': 'rgb(var(--cta-hover) / <alpha-value>)',
        'on-cta': 'rgb(var(--on-cta) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['Archivo', 'system-ui', 'sans-serif'],
        display: ['Archivo', 'system-ui', 'sans-serif'],
        logo: ['Skaldheim', 'Archivo', 'serif'],
      },
      spacing: {
        'safe-top':    'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left':   'env(safe-area-inset-left)',
        'safe-right':  'env(safe-area-inset-right)',
      },
      maxWidth: {
        app: '1400px',
      },
      screens: {
        xs: '400px',
      },
      keyframes: {
        shimmer: {
          '100%': { transform: 'translateX(100%)' },
        },
        'toast-in': {
          from: { opacity: '0', transform: 'translateX(100%)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%, 60%': { transform: 'translateX(-8px)' },
          '40%, 80%': { transform: 'translateX(8px)' },
        },
        'loading-bar': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(400%)' },
        },
        'stone-climb': {
          '0%':   { transform: 'translate(0,0) rotate(0deg)', opacity: '0' },
          '5%':   { transform: 'translate(10px,-4.6px) rotate(63deg)', opacity: '1' },
          '50%':  {
            transform: 'translate(130px,-59.2px) rotate(816deg)',
            opacity: '1',
            animationTimingFunction: 'cubic-bezier(.55,0,.9,.35)',
          },
          '58%':  { transform: 'translate(110px,-50.1px) rotate(691deg)', opacity: '1' },
          '90%':  { transform: 'translate(200px,-91px) rotate(1256deg)', opacity: '1' },
          '97%':  { transform: 'translate(200px,-91px) rotate(1256deg)', opacity: '0' },
          '100%': { transform: 'translate(0,0) rotate(0deg)', opacity: '0' },
        },
        'stone-summit': {
          '0%':   { transform: 'translate(130px,-59.2px) rotate(816deg)', opacity: '0' },
          '18%':  { opacity: '1' },
          '100%': { transform: 'translate(200px,-91px) rotate(1256deg)', opacity: '1' },
        },
        'ring-seal': {
          '0%':   { transform: 'scale(1)' },
          '35%':  { transform: 'scale(1.045)' },
          '100%': { transform: 'scale(1)' },
        },
        'ring-glow': {
          '0%, 100%': { opacity: '0' },
          '22%, 58%': { opacity: '1' },
        },
        'rise-in': {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        shimmer:       'shimmer 1.5s infinite',
        'toast-in':    'toast-in 0.3s ease-out',
        'fade-in':     'fade-in 0.2s ease-out',
        'shake':       'shake 0.4s ease-in-out',
        'loading-bar': 'loading-bar 1.4s ease-in-out infinite',
        'stone-climb':  'stone-climb 6.5s ease-in-out infinite',
        'stone-summit': 'stone-summit 900ms var(--ease-out) forwards',
        'ring-seal':    'ring-seal var(--dur-moment) var(--ease-out)',
        'ring-glow':    'ring-glow var(--dur-moment) ease-out',
        'rise-in':      'rise-in 500ms var(--ease-out)',
      },
      transitionTimingFunction: {
        brand: 'var(--ease-out)',
      },
      transitionDuration: {
        tap: 'var(--dur-tap)',
        ui: 'var(--dur-ui)',
        panel: 'var(--dur-panel)',
        moment: 'var(--dur-moment)',
      },
    },
  },
  plugins: [],
};